// This file is autogenerated by ragel. Do not modify it manually!

#line 1 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
#include "lexer.h"

#include "errors.h"
#include "io.h"
#include "tokens.h"

#include <assert.h>
#include <string.h>
#include <stdlib.h>

#include <stdio.h> // snprintf

#define MATCH_START\
    token_entry = p

#define LINE_START\
    last_nl = p

#define TOKEN_W_LEXEME(tok)\
    push_token_w_lexeme(tok, token_entry, p, source_location_create(filename, current_line, token_entry - last_nl), &records)

#define TOKEN_WO_LEXEME(tok)\
    push_token_wo_lexeme(tok, source_location_create(filename, current_line, token_entry - last_nl), &records)


#line 71 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"



#line 28 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
static const int lexer_start = 77;
static const int lexer_first_final = 77;
static const int lexer_error = -1;

static const int lexer_en_skip_ln = 91;
static const int lexer_en_main = 77;


#line 74 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"

enum lex_error
{
    LEX_ERROR_UNRECOGNIZED_LINE,
    LEX_ERROR_FILE_IO,
    LEX_ERROR_BUFFER_OUT_OF_SPACE,

    _LEX_ERROR_COUNT
};

char const* lex_error_fmts[_LEX_ERROR_COUNT] =
{
    "unrecognized line",
    "file io error",
    "buffer out of space"
};

static void push_lex_error(enum lex_error error, opaque_vector* errors, char const* filename, int line)
{
    assert(filename != NULL);
    assert(error >= 0 && error < _LEX_ERROR_COUNT);
    assert(errors != NULL);

    #define LEX_ERROR_MSG_LEN 128

    char msg[LEX_ERROR_MSG_LEN];
    snprintf(msg, LEX_ERROR_MSG_LEN, lex_error_fmts[error]);
    opaque_vector_push(errors, &(file_error){.message = strdup(msg), .loc = source_location_create(filename, line, 0)});
}

static void remove_tokens_w_line(int line, opaque_vector* v_rec)
{
    assert(v_rec != NULL);

    size_t size = opaque_vector_size(v_rec);
    while (size > 0)
    {
        token_record const* back = opaque_vector_at(v_rec, size - 1);

        if (back->loc.line != line)
            break;

        opaque_vector_pop(v_rec);
        size = opaque_vector_size(v_rec);
    }
}

void push_token_w_lexeme(int tok, char* ts, char* te, source_location loc, opaque_vector* v_rec)
{
    int const lexeme_len = te - ts;
    char* lexeme = (char*)malloc(lexeme_len + 1);
    memcpy(lexeme, ts, lexeme_len);
    lexeme[lexeme_len] = '\0';

    token_record rec;
    rec.token = tok;
    rec.loc = loc;
    rec.lexeme = lexeme;

    opaque_vector_push(v_rec, &rec);
}

void push_token_wo_lexeme(int tok, source_location loc, opaque_vector* v_rec)
{
    token_record rec;
    rec.token = tok;
    rec.loc = loc;
    rec.lexeme = NULL;

    opaque_vector_push(v_rec, &rec);
}

opaque_vector lex(char const* filename, char* buffer, int bufsz, opaque_vector* errors)
{
    assert(filename != NULL);
    assert(errors != NULL);
    assert(buffer != NULL);
    assert(bufsz > 1);

            // See ch 5.1 in the ragel manual
    char* p = NULL;   // Data pointer
    char* pe = NULL;  // Data end pointer
    char* eof = NULL; // EOF pointer (== pe for last block, otherwise null)
    char* ts = NULL;  // Token start
    char* te = NULL;  // Token end
    int   cs = 0;     // Current state
    int   act = 0;    // Current action

    char* data = NULL;
    char* token_entry = NULL; // pointer to where a match started
    char* last_nl = buffer;   // pointer to after the last newline
    int leftover = 0;
    int space = 0;
    int len = 0;
    int current_line = 1;

    int const errors_at_start = opaque_vector_size(errors);

    
#line 133 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	{
	cs = lexer_start;
	ts = 0;
	te = 0;
	act = 0;
	}

#line 173 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"

    opaque_vector records = opaque_vector_create(sizeof(token_record), token_record_destroy);
    terminated_reader reader = terminated_reader_create(filename, "\n", 1);

    if (!reader || terminated_reader_error(reader))
    {
        push_lex_error(LEX_ERROR_FILE_IO, errors, filename, current_line);
        goto ret_stmt;
    }

    do
    {
        space = bufsz - leftover;

        if (space == 0)
        {
            push_lex_error(LEX_ERROR_BUFFER_OUT_OF_SPACE, errors, filename, current_line);
            break;
        }

        data = buffer + leftover;
        len = terminated_reader_read(reader, data, space);

        if (terminated_reader_error(reader))
        {
            push_lex_error(LEX_ERROR_FILE_IO, errors, filename, current_line);
            break;
        }

        // find last nl by searching backwards
        p = buffer;
        pe = buffer + leftover + len - 1;
        while (pe > buffer && *pe != '\n')
            pe--;

            // could not find a newline, the buffer is too small
        if (pe++ == buffer)
        {
            push_lex_error(LEX_ERROR_BUFFER_OUT_OF_SPACE, errors, filename, current_line);
            break;
        }

            // inform ragel if we are at the final buffer block
        eof = terminated_reader_done(reader) ? pe : NULL;

        
#line 184 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	{
	if ( p == pe )
		goto _test_eof;
	switch ( cs )
	{
tr0:
#line 51 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{{p = ((te))-1;}{
        remove_tokens_w_line(current_line, &records);
        push_lex_error(LEX_ERROR_UNRECOGNIZED_LINE, errors, filename, current_line);
        {goto st91;}
    }}
	goto st77;
tr136:
#line 51 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{te = p+1;{
        remove_tokens_w_line(current_line, &records);
        push_lex_error(LEX_ERROR_UNRECOGNIZED_LINE, errors, filename, current_line);
        {goto st91;}
    }}
	goto st77;
tr144:
#line 51 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{te = p;p--;{
        remove_tokens_w_line(current_line, &records);
        push_lex_error(LEX_ERROR_UNRECOGNIZED_LINE, errors, filename, current_line);
        {goto st91;}
    }}
	goto st77;
tr145:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{LINE_START;}
#line 68 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{te = p;p--;}
	goto st77;
tr146:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{LINE_START;}
#line 63 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{te = p;p--;}
	goto st77;
tr147:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{LINE_START;}
#line 67 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{te = p;p--;}
	goto st77;
tr148:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{LINE_START;}
#line 66 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{te = p;p--;}
	goto st77;
tr149:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{LINE_START;}
#line 64 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{te = p;p--;}
	goto st77;
tr150:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{LINE_START;}
#line 65 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{te = p;p--;}
	goto st77;
st77:
#line 1 "NONE"
	{ts = 0;}
	if ( ++p == pe )
		goto _test_eof77;
case 77:
#line 1 "NONE"
	{ts = p;}
#line 240 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr2;
		case 13: goto tr138;
		case 32: goto tr137;
		case 35: goto tr139;
		case 95: goto tr141;
		case 97: goto tr142;
		case 118: goto tr143;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 12 )
			goto tr137;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 98 <= (*p) && (*p) <= 122 )
				goto tr141;
		} else if ( (*p) >= 65 )
			goto tr141;
	} else
		goto tr140;
	goto tr136;
tr137:
#line 1 "NONE"
	{te = p+1;}
	goto st78;
st78:
	if ( ++p == pe )
		goto _test_eof78;
case 78:
#line 268 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr2;
		case 13: goto tr3;
		case 32: goto st0;
		case 35: goto st2;
		case 95: goto tr6;
		case 97: goto tr7;
		case 118: goto tr8;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 12 )
			goto st0;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 98 <= (*p) && (*p) <= 122 )
				goto tr6;
		} else if ( (*p) >= 65 )
			goto tr6;
	} else
		goto tr5;
	goto tr144;
st0:
	if ( ++p == pe )
		goto _test_eof0;
case 0:
	switch( (*p) ) {
		case 10: goto tr2;
		case 13: goto tr3;
		case 32: goto st0;
		case 35: goto st2;
		case 95: goto tr6;
		case 97: goto tr7;
		case 118: goto tr8;
	}
	if ( (*p) < 48 ) {
		if ( 9 <= (*p) && (*p) <= 12 )
			goto st0;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 98 <= (*p) && (*p) <= 122 )
				goto tr6;
		} else if ( (*p) >= 65 )
			goto tr6;
	} else
		goto tr5;
	goto tr0;
tr2:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st79;
st79:
	if ( ++p == pe )
		goto _test_eof79;
case 79:
#line 321 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	goto tr145;
tr3:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st1;
st1:
	if ( ++p == pe )
		goto _test_eof1;
case 1:
#line 329 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	if ( (*p) == 10 )
		goto st79;
	goto tr0;
st2:
	if ( ++p == pe )
		goto _test_eof2;
case 2:
	switch( (*p) ) {
		case 10: goto tr2;
		case 13: goto tr3;
	}
	if ( 32 <= (*p) && (*p) <= 126 )
		goto st2;
	goto tr0;
tr5:
#line 39 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st3;
st3:
	if ( ++p == pe )
		goto _test_eof3;
case 3:
#line 350 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	if ( 48 <= (*p) && (*p) <= 57 )
		goto st4;
	goto tr0;
st4:
	if ( ++p == pe )
		goto _test_eof4;
case 4:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto st5;
	goto tr0;
st5:
	if ( ++p == pe )
		goto _test_eof5;
case 5:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto st6;
	goto tr0;
st6:
	if ( ++p == pe )
		goto _test_eof6;
case 6:
	if ( (*p) == 45 )
		goto st7;
	goto tr0;
st7:
	if ( ++p == pe )
		goto _test_eof7;
case 7:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto st8;
	goto tr0;
st8:
	if ( ++p == pe )
		goto _test_eof8;
case 8:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto st9;
	goto tr0;
st9:
	if ( ++p == pe )
		goto _test_eof9;
case 9:
	if ( (*p) == 45 )
		goto st10;
	goto tr0;
st10:
	if ( ++p == pe )
		goto _test_eof10;
case 10:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto st11;
	goto tr0;
st11:
	if ( ++p == pe )
		goto _test_eof11;
case 11:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto st12;
	goto tr0;
st12:
	if ( ++p == pe )
		goto _test_eof12;
case 12:
	switch( (*p) ) {
		case 10: goto tr20;
		case 13: goto tr21;
		case 32: goto tr19;
		case 35: goto tr22;
	}
	if ( 9 <= (*p) && (*p) <= 12 )
		goto tr19;
	goto tr0;
tr19:
#line 39 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_W_LEXEME(TOKEN_DATE);}
	goto st13;
st13:
	if ( ++p == pe )
		goto _test_eof13;
case 13:
#line 429 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr24;
		case 13: goto tr25;
		case 32: goto st13;
		case 35: goto st15;
	}
	if ( 9 <= (*p) && (*p) <= 12 )
		goto st13;
	goto tr0;
tr24:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st80;
tr20:
#line 39 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_W_LEXEME(TOKEN_DATE);}
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st80;
st80:
	if ( ++p == pe )
		goto _test_eof80;
case 80:
#line 449 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	goto tr146;
tr25:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st14;
tr21:
#line 39 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_W_LEXEME(TOKEN_DATE);}
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st14;
st14:
	if ( ++p == pe )
		goto _test_eof14;
case 14:
#line 461 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	if ( (*p) == 10 )
		goto st80;
	goto tr0;
tr22:
#line 39 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_W_LEXEME(TOKEN_DATE);}
	goto st15;
st15:
	if ( ++p == pe )
		goto _test_eof15;
case 15:
#line 471 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr24;
		case 13: goto tr25;
	}
	if ( 32 <= (*p) && (*p) <= 126 )
		goto st15;
	goto tr0;
tr6:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st16;
st16:
	if ( ++p == pe )
		goto _test_eof16;
case 16:
#line 485 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr28;
		case 32: goto tr28;
		case 46: goto st16;
		case 58: goto tr30;
		case 95: goto st16;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr28;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st16;
		} else if ( (*p) >= 65 )
			goto st16;
	} else
		goto st16;
	goto tr0;
tr28:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_W_LEXEME(TOKEN_IDENT);}
	goto st17;
st17:
	if ( ++p == pe )
		goto _test_eof17;
case 17:
#line 511 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto st17;
		case 32: goto st17;
	}
	if ( (*p) < 33 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto st17;
	} else if ( (*p) > 34 ) {
		if ( (*p) > 58 ) {
			if ( 60 <= (*p) && (*p) <= 126 )
				goto tr32;
		} else if ( (*p) >= 36 )
			goto tr32;
	} else
		goto tr32;
	goto tr0;
tr32:
#line 40 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st18;
st18:
	if ( ++p == pe )
		goto _test_eof18;
case 18:
#line 534 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr33;
		case 32: goto tr33;
		case 59: goto tr35;
	}
	if ( (*p) < 33 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr33;
	} else if ( (*p) > 34 ) {
		if ( 36 <= (*p) && (*p) <= 126 )
			goto st18;
	} else
		goto st18;
	goto tr0;
tr33:
#line 40 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_W_LEXEME(TOKEN_ATTR_VALUE);}
	goto st19;
st19:
	if ( ++p == pe )
		goto _test_eof19;
case 19:
#line 555 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto st19;
		case 32: goto st19;
		case 59: goto tr37;
	}
	if ( 11 <= (*p) && (*p) <= 12 )
		goto st19;
	goto tr0;
tr35:
#line 40 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_W_LEXEME(TOKEN_ATTR_VALUE);}
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st20;
tr37:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st20;
st20:
	if ( ++p == pe )
		goto _test_eof20;
case 20:
#line 574 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr39;
		case 13: goto tr40;
		case 32: goto tr38;
		case 35: goto tr41;
		case 95: goto tr42;
		case 97: goto tr43;
		case 118: goto tr44;
	}
	if ( (*p) < 65 ) {
		if ( 9 <= (*p) && (*p) <= 12 )
			goto tr38;
	} else if ( (*p) > 90 ) {
		if ( 98 <= (*p) && (*p) <= 122 )
			goto tr42;
	} else
		goto tr42;
	goto tr0;
tr38:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
	goto st21;
st21:
	if ( ++p == pe )
		goto _test_eof21;
case 21:
#line 599 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr46;
		case 13: goto tr47;
		case 32: goto st21;
		case 35: goto st23;
		case 95: goto tr49;
		case 97: goto tr50;
		case 118: goto tr51;
	}
	if ( (*p) < 65 ) {
		if ( 9 <= (*p) && (*p) <= 12 )
			goto st21;
	} else if ( (*p) > 90 ) {
		if ( 98 <= (*p) && (*p) <= 122 )
			goto tr49;
	} else
		goto tr49;
	goto tr0;
tr46:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st81;
tr39:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st81;
st81:
	if ( ++p == pe )
		goto _test_eof81;
case 81:
#line 628 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	goto tr147;
tr47:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st22;
tr40:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st22;
st22:
	if ( ++p == pe )
		goto _test_eof22;
case 22:
#line 640 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	if ( (*p) == 10 )
		goto st81;
	goto tr0;
tr41:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
	goto st23;
st23:
	if ( ++p == pe )
		goto _test_eof23;
case 23:
#line 650 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr46;
		case 13: goto tr47;
	}
	if ( 32 <= (*p) && (*p) <= 126 )
		goto st23;
	goto tr0;
tr49:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st24;
tr42:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st24;
st24:
	if ( ++p == pe )
		goto _test_eof24;
case 24:
#line 668 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr28;
		case 32: goto tr28;
		case 46: goto st24;
		case 95: goto st24;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr28;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st24;
		} else if ( (*p) >= 65 )
			goto st24;
	} else
		goto st24;
	goto tr0;
tr43:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 33 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st25;
tr50:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 33 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st25;
st25:
	if ( ++p == pe )
		goto _test_eof25;
case 25:
#line 699 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr28;
		case 32: goto tr28;
		case 46: goto st24;
		case 95: goto st24;
		case 116: goto st26;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr28;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st24;
		} else if ( (*p) >= 65 )
			goto st24;
	} else
		goto st24;
	goto tr0;
st26:
	if ( ++p == pe )
		goto _test_eof26;
case 26:
	switch( (*p) ) {
		case 9: goto tr28;
		case 32: goto tr28;
		case 46: goto st24;
		case 95: goto st24;
		case 116: goto st27;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr28;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st24;
		} else if ( (*p) >= 65 )
			goto st24;
	} else
		goto st24;
	goto tr0;
st27:
	if ( ++p == pe )
		goto _test_eof27;
case 27:
	switch( (*p) ) {
		case 9: goto tr28;
		case 32: goto tr28;
		case 46: goto st24;
		case 95: goto st24;
		case 114: goto st28;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr28;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st24;
		} else if ( (*p) >= 65 )
			goto st24;
	} else
		goto st24;
	goto tr0;
st28:
	if ( ++p == pe )
		goto _test_eof28;
case 28:
	switch( (*p) ) {
		case 46: goto st24;
		case 95: goto st24;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto st24;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st24;
	} else
		goto st24;
	goto tr0;
tr44:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 32 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st29;
tr51:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 32 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st29;
st29:
	if ( ++p == pe )
		goto _test_eof29;
case 29:
#line 794 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr28;
		case 32: goto tr28;
		case 46: goto st24;
		case 95: goto st24;
		case 97: goto st27;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr28;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 98 <= (*p) && (*p) <= 122 )
				goto st24;
		} else if ( (*p) >= 65 )
			goto st24;
	} else
		goto st24;
	goto tr0;
tr30:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_W_LEXEME(TOKEN_IDENT);}
#line 34 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st30;
st30:
	if ( ++p == pe )
		goto _test_eof30;
case 30:
#line 821 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr58;
		case 13: goto tr59;
		case 32: goto tr57;
		case 35: goto tr60;
	}
	if ( 9 <= (*p) && (*p) <= 12 )
		goto tr57;
	goto tr0;
tr57:
#line 34 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_COLON);}
	goto st31;
st31:
	if ( ++p == pe )
		goto _test_eof31;
case 31:
#line 837 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr62;
		case 13: goto tr63;
		case 32: goto st31;
		case 35: goto st33;
	}
	if ( 9 <= (*p) && (*p) <= 12 )
		goto st31;
	goto tr0;
tr62:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st82;
tr58:
#line 34 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_COLON);}
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st82;
st82:
	if ( ++p == pe )
		goto _test_eof82;
case 82:
#line 857 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	goto tr148;
tr63:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st32;
tr59:
#line 34 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_COLON);}
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st32;
st32:
	if ( ++p == pe )
		goto _test_eof32;
case 32:
#line 869 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	if ( (*p) == 10 )
		goto st82;
	goto tr0;
tr60:
#line 34 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_COLON);}
	goto st33;
st33:
	if ( ++p == pe )
		goto _test_eof33;
case 33:
#line 879 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr62;
		case 13: goto tr63;
	}
	if ( 32 <= (*p) && (*p) <= 126 )
		goto st33;
	goto tr0;
tr7:
#line 33 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st34;
st34:
	if ( ++p == pe )
		goto _test_eof34;
case 34:
#line 894 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr28;
		case 32: goto tr28;
		case 46: goto st16;
		case 58: goto tr30;
		case 95: goto st16;
		case 116: goto st35;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr28;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st16;
		} else if ( (*p) >= 65 )
			goto st16;
	} else
		goto st16;
	goto tr0;
st35:
	if ( ++p == pe )
		goto _test_eof35;
case 35:
	switch( (*p) ) {
		case 9: goto tr28;
		case 32: goto tr28;
		case 46: goto st16;
		case 58: goto tr30;
		case 95: goto st16;
		case 116: goto st36;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr28;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st16;
		} else if ( (*p) >= 65 )
			goto st16;
	} else
		goto st16;
	goto tr0;
st36:
	if ( ++p == pe )
		goto _test_eof36;
case 36:
	switch( (*p) ) {
		case 9: goto tr28;
		case 32: goto tr28;
		case 46: goto st16;
		case 58: goto tr30;
		case 95: goto st16;
		case 114: goto st37;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr28;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st16;
		} else if ( (*p) >= 65 )
			goto st16;
	} else
		goto st16;
	goto tr0;
st37:
	if ( ++p == pe )
		goto _test_eof37;
case 37:
	switch( (*p) ) {
		case 46: goto st16;
		case 58: goto tr69;
		case 95: goto st16;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto st16;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st16;
	} else
		goto st16;
	goto tr0;
tr69:
#line 33 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_DECL_ATTR);}
#line 34 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st38;
st38:
	if ( ++p == pe )
		goto _test_eof38;
case 38:
#line 988 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr70;
		case 32: goto tr70;
	}
	if ( 11 <= (*p) && (*p) <= 12 )
		goto tr70;
	goto tr0;
tr70:
#line 34 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_COLON);}
	goto st39;
st39:
	if ( ++p == pe )
		goto _test_eof39;
case 39:
#line 1002 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto st39;
		case 32: goto st39;
		case 95: goto tr72;
		case 97: goto tr73;
		case 118: goto tr74;
	}
	if ( (*p) < 65 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto st39;
	} else if ( (*p) > 90 ) {
		if ( 98 <= (*p) && (*p) <= 122 )
			goto tr72;
	} else
		goto tr72;
	goto tr0;
tr72:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st40;
st40:
	if ( ++p == pe )
		goto _test_eof40;
case 40:
#line 1025 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr75;
		case 32: goto tr75;
		case 46: goto st40;
		case 95: goto st40;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr75;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st40;
		} else if ( (*p) >= 65 )
			goto st40;
	} else
		goto st40;
	goto tr0;
tr75:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_W_LEXEME(TOKEN_IDENT);}
	goto st41;
tr90:
#line 38 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_W_LEXEME(TOKEN_REGEX);}
	goto st41;
st41:
	if ( ++p == pe )
		goto _test_eof41;
case 41:
#line 1053 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto st41;
		case 32: goto st41;
		case 59: goto tr78;
	}
	if ( 11 <= (*p) && (*p) <= 12 )
		goto st41;
	goto tr0;
tr78:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st42;
tr92:
#line 38 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_W_LEXEME(TOKEN_REGEX);}
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st42;
st42:
	if ( ++p == pe )
		goto _test_eof42;
case 42:
#line 1072 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr80;
		case 13: goto tr81;
		case 32: goto tr79;
		case 35: goto tr83;
	}
	if ( (*p) < 33 ) {
		if ( 9 <= (*p) && (*p) <= 12 )
			goto tr79;
	} else if ( (*p) > 58 ) {
		if ( 60 <= (*p) && (*p) <= 126 )
			goto tr82;
	} else
		goto tr82;
	goto tr0;
tr79:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
	goto st43;
st43:
	if ( ++p == pe )
		goto _test_eof43;
case 43:
#line 1094 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr85;
		case 13: goto tr86;
		case 32: goto st43;
		case 35: goto st46;
	}
	if ( (*p) < 33 ) {
		if ( 9 <= (*p) && (*p) <= 12 )
			goto st43;
	} else if ( (*p) > 58 ) {
		if ( 60 <= (*p) && (*p) <= 126 )
			goto tr87;
	} else
		goto tr87;
	goto tr0;
tr85:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st83;
tr80:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st83;
st83:
	if ( ++p == pe )
		goto _test_eof83;
case 83:
#line 1120 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	goto tr149;
tr86:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st44;
tr81:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st44;
st44:
	if ( ++p == pe )
		goto _test_eof44;
case 44:
#line 1132 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	if ( (*p) == 10 )
		goto st83;
	goto tr0;
tr82:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
#line 38 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st45;
tr87:
#line 38 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st45;
st45:
	if ( ++p == pe )
		goto _test_eof45;
case 45:
#line 1146 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr90;
		case 32: goto tr90;
		case 59: goto tr92;
	}
	if ( (*p) < 33 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr90;
	} else if ( (*p) > 34 ) {
		if ( 36 <= (*p) && (*p) <= 126 )
			goto st45;
	} else
		goto st45;
	goto tr0;
tr83:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
	goto st46;
st46:
	if ( ++p == pe )
		goto _test_eof46;
case 46:
#line 1167 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr85;
		case 13: goto tr86;
	}
	if ( 32 <= (*p) && (*p) <= 126 )
		goto st46;
	goto tr0;
tr73:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 33 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st47;
st47:
	if ( ++p == pe )
		goto _test_eof47;
case 47:
#line 1182 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr75;
		case 32: goto tr75;
		case 46: goto st40;
		case 95: goto st40;
		case 116: goto st48;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr75;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st40;
		} else if ( (*p) >= 65 )
			goto st40;
	} else
		goto st40;
	goto tr0;
st48:
	if ( ++p == pe )
		goto _test_eof48;
case 48:
	switch( (*p) ) {
		case 9: goto tr75;
		case 32: goto tr75;
		case 46: goto st40;
		case 95: goto st40;
		case 116: goto st49;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr75;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st40;
		} else if ( (*p) >= 65 )
			goto st40;
	} else
		goto st40;
	goto tr0;
st49:
	if ( ++p == pe )
		goto _test_eof49;
case 49:
	switch( (*p) ) {
		case 9: goto tr75;
		case 32: goto tr75;
		case 46: goto st40;
		case 95: goto st40;
		case 114: goto st50;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr75;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st40;
		} else if ( (*p) >= 65 )
			goto st40;
	} else
		goto st40;
	goto tr0;
st50:
	if ( ++p == pe )
		goto _test_eof50;
case 50:
	switch( (*p) ) {
		case 46: goto st40;
		case 95: goto st40;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto st40;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st40;
	} else
		goto st40;
	goto tr0;
tr74:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 32 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st51;
st51:
	if ( ++p == pe )
		goto _test_eof51;
case 51:
#line 1272 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr75;
		case 32: goto tr75;
		case 46: goto st40;
		case 95: goto st40;
		case 97: goto st49;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr75;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 98 <= (*p) && (*p) <= 122 )
				goto st40;
		} else if ( (*p) >= 65 )
			goto st40;
	} else
		goto st40;
	goto tr0;
tr8:
#line 32 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st52;
st52:
	if ( ++p == pe )
		goto _test_eof52;
case 52:
#line 1299 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr28;
		case 32: goto tr28;
		case 46: goto st16;
		case 58: goto tr30;
		case 95: goto st16;
		case 97: goto st53;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr28;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 98 <= (*p) && (*p) <= 122 )
				goto st16;
		} else if ( (*p) >= 65 )
			goto st16;
	} else
		goto st16;
	goto tr0;
st53:
	if ( ++p == pe )
		goto _test_eof53;
case 53:
	switch( (*p) ) {
		case 9: goto tr28;
		case 32: goto tr28;
		case 46: goto st16;
		case 58: goto tr30;
		case 95: goto st16;
		case 114: goto st54;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr28;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st16;
		} else if ( (*p) >= 65 )
			goto st16;
	} else
		goto st16;
	goto tr0;
st54:
	if ( ++p == pe )
		goto _test_eof54;
case 54:
	switch( (*p) ) {
		case 46: goto st16;
		case 58: goto tr98;
		case 95: goto st16;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto st16;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st16;
	} else
		goto st16;
	goto tr0;
tr98:
#line 32 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_DECL_VAR);}
#line 34 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st55;
st55:
	if ( ++p == pe )
		goto _test_eof55;
case 55:
#line 1369 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr99;
		case 32: goto tr99;
	}
	if ( 11 <= (*p) && (*p) <= 12 )
		goto tr99;
	goto tr0;
tr99:
#line 34 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_COLON);}
	goto st56;
st56:
	if ( ++p == pe )
		goto _test_eof56;
case 56:
#line 1383 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto st56;
		case 32: goto st56;
		case 95: goto tr101;
		case 97: goto tr102;
		case 118: goto tr103;
	}
	if ( (*p) < 65 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto st56;
	} else if ( (*p) > 90 ) {
		if ( 98 <= (*p) && (*p) <= 122 )
			goto tr101;
	} else
		goto tr101;
	goto tr0;
tr101:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st57;
st57:
	if ( ++p == pe )
		goto _test_eof57;
case 57:
#line 1406 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr104;
		case 32: goto tr104;
		case 46: goto st57;
		case 95: goto st57;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr104;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st57;
		} else if ( (*p) >= 65 )
			goto st57;
	} else
		goto st57;
	goto tr0;
tr104:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_W_LEXEME(TOKEN_IDENT);}
	goto st58;
st58:
	if ( ++p == pe )
		goto _test_eof58;
case 58:
#line 1431 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto st58;
		case 32: goto st58;
		case 59: goto tr107;
	}
	if ( 11 <= (*p) && (*p) <= 12 )
		goto st58;
	goto tr0;
tr107:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st59;
st59:
	if ( ++p == pe )
		goto _test_eof59;
case 59:
#line 1446 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr108;
		case 32: goto tr108;
		case 95: goto tr109;
		case 97: goto tr110;
		case 118: goto tr111;
	}
	if ( (*p) < 65 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr108;
	} else if ( (*p) > 90 ) {
		if ( 98 <= (*p) && (*p) <= 122 )
			goto tr109;
	} else
		goto tr109;
	goto tr0;
tr108:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
	goto st60;
st60:
	if ( ++p == pe )
		goto _test_eof60;
case 60:
#line 1469 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto st60;
		case 32: goto st60;
		case 95: goto tr113;
		case 97: goto tr114;
		case 118: goto tr115;
	}
	if ( (*p) < 65 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto st60;
	} else if ( (*p) > 90 ) {
		if ( 98 <= (*p) && (*p) <= 122 )
			goto tr113;
	} else
		goto tr113;
	goto tr0;
tr113:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st61;
tr109:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st61;
st61:
	if ( ++p == pe )
		goto _test_eof61;
case 61:
#line 1496 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr116;
		case 32: goto tr116;
		case 46: goto st61;
		case 59: goto tr118;
		case 95: goto st61;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr116;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st61;
		} else if ( (*p) >= 65 )
			goto st61;
	} else
		goto st61;
	goto tr0;
tr116:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_W_LEXEME(TOKEN_IDENT);}
	goto st62;
st62:
	if ( ++p == pe )
		goto _test_eof62;
case 62:
#line 1522 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto st62;
		case 32: goto st62;
		case 59: goto tr120;
	}
	if ( 11 <= (*p) && (*p) <= 12 )
		goto st62;
	goto tr0;
tr120:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st63;
tr118:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_W_LEXEME(TOKEN_IDENT);}
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st63;
st63:
	if ( ++p == pe )
		goto _test_eof63;
case 63:
#line 1541 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr122;
		case 13: goto tr123;
		case 32: goto tr121;
		case 35: goto tr124;
		case 95: goto tr109;
		case 97: goto tr110;
		case 118: goto tr111;
	}
	if ( (*p) < 65 ) {
		if ( 9 <= (*p) && (*p) <= 12 )
			goto tr121;
	} else if ( (*p) > 90 ) {
		if ( 98 <= (*p) && (*p) <= 122 )
			goto tr109;
	} else
		goto tr109;
	goto tr0;
tr121:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
	goto st64;
st64:
	if ( ++p == pe )
		goto _test_eof64;
case 64:
#line 1566 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr126;
		case 13: goto tr127;
		case 32: goto st64;
		case 35: goto st66;
		case 95: goto tr113;
		case 97: goto tr114;
		case 118: goto tr115;
	}
	if ( (*p) < 65 ) {
		if ( 9 <= (*p) && (*p) <= 12 )
			goto st64;
	} else if ( (*p) > 90 ) {
		if ( 98 <= (*p) && (*p) <= 122 )
			goto tr113;
	} else
		goto tr113;
	goto tr0;
tr126:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st84;
tr122:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st84;
st84:
	if ( ++p == pe )
		goto _test_eof84;
case 84:
#line 1595 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	goto tr150;
tr127:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st65;
tr123:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st65;
st65:
	if ( ++p == pe )
		goto _test_eof65;
case 65:
#line 1607 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	if ( (*p) == 10 )
		goto st84;
	goto tr0;
tr124:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
	goto st66;
st66:
	if ( ++p == pe )
		goto _test_eof66;
case 66:
#line 1617 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr126;
		case 13: goto tr127;
	}
	if ( 32 <= (*p) && (*p) <= 126 )
		goto st66;
	goto tr0;
tr110:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 33 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st67;
tr114:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 33 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st67;
st67:
	if ( ++p == pe )
		goto _test_eof67;
case 67:
#line 1637 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr116;
		case 32: goto tr116;
		case 46: goto st61;
		case 59: goto tr118;
		case 95: goto st61;
		case 116: goto st68;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr116;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st61;
		} else if ( (*p) >= 65 )
			goto st61;
	} else
		goto st61;
	goto tr0;
st68:
	if ( ++p == pe )
		goto _test_eof68;
case 68:
	switch( (*p) ) {
		case 9: goto tr116;
		case 32: goto tr116;
		case 46: goto st61;
		case 59: goto tr118;
		case 95: goto st61;
		case 116: goto st69;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr116;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st61;
		} else if ( (*p) >= 65 )
			goto st61;
	} else
		goto st61;
	goto tr0;
st69:
	if ( ++p == pe )
		goto _test_eof69;
case 69:
	switch( (*p) ) {
		case 9: goto tr116;
		case 32: goto tr116;
		case 46: goto st61;
		case 59: goto tr118;
		case 95: goto st61;
		case 114: goto st70;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr116;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st61;
		} else if ( (*p) >= 65 )
			goto st61;
	} else
		goto st61;
	goto tr0;
st70:
	if ( ++p == pe )
		goto _test_eof70;
case 70:
	switch( (*p) ) {
		case 46: goto st61;
		case 95: goto st61;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto st61;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st61;
	} else
		goto st61;
	goto tr0;
tr111:
#line 35 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{TOKEN_WO_LEXEME(TOKEN_SEMICOLON);}
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 32 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st71;
tr115:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 32 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st71;
st71:
	if ( ++p == pe )
		goto _test_eof71;
case 71:
#line 1735 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr116;
		case 32: goto tr116;
		case 46: goto st61;
		case 59: goto tr118;
		case 95: goto st61;
		case 97: goto st69;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr116;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 98 <= (*p) && (*p) <= 122 )
				goto st61;
		} else if ( (*p) >= 65 )
			goto st61;
	} else
		goto st61;
	goto tr0;
tr102:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 33 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st72;
st72:
	if ( ++p == pe )
		goto _test_eof72;
case 72:
#line 1763 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr104;
		case 32: goto tr104;
		case 46: goto st57;
		case 95: goto st57;
		case 116: goto st73;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr104;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st57;
		} else if ( (*p) >= 65 )
			goto st57;
	} else
		goto st57;
	goto tr0;
st73:
	if ( ++p == pe )
		goto _test_eof73;
case 73:
	switch( (*p) ) {
		case 9: goto tr104;
		case 32: goto tr104;
		case 46: goto st57;
		case 95: goto st57;
		case 116: goto st74;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr104;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st57;
		} else if ( (*p) >= 65 )
			goto st57;
	} else
		goto st57;
	goto tr0;
st74:
	if ( ++p == pe )
		goto _test_eof74;
case 74:
	switch( (*p) ) {
		case 9: goto tr104;
		case 32: goto tr104;
		case 46: goto st57;
		case 95: goto st57;
		case 114: goto st75;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr104;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st57;
		} else if ( (*p) >= 65 )
			goto st57;
	} else
		goto st57;
	goto tr0;
st75:
	if ( ++p == pe )
		goto _test_eof75;
case 75:
	switch( (*p) ) {
		case 46: goto st57;
		case 95: goto st57;
	}
	if ( (*p) < 65 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto st57;
	} else if ( (*p) > 90 ) {
		if ( 97 <= (*p) && (*p) <= 122 )
			goto st57;
	} else
		goto st57;
	goto tr0;
tr103:
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 32 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st76;
st76:
	if ( ++p == pe )
		goto _test_eof76;
case 76:
#line 1853 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr104;
		case 32: goto tr104;
		case 46: goto st57;
		case 95: goto st57;
		case 97: goto st74;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr104;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 98 <= (*p) && (*p) <= 122 )
				goto st57;
		} else if ( (*p) >= 65 )
			goto st57;
	} else
		goto st57;
	goto tr0;
tr138:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st85;
st85:
	if ( ++p == pe )
		goto _test_eof85;
case 85:
#line 1879 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	if ( (*p) == 10 )
		goto st79;
	goto tr144;
tr139:
#line 1 "NONE"
	{te = p+1;}
	goto st86;
st86:
	if ( ++p == pe )
		goto _test_eof86;
case 86:
#line 1889 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr2;
		case 13: goto tr3;
	}
	if ( 32 <= (*p) && (*p) <= 126 )
		goto st2;
	goto tr144;
tr140:
#line 1 "NONE"
	{te = p+1;}
#line 39 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st87;
st87:
	if ( ++p == pe )
		goto _test_eof87;
case 87:
#line 1904 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	if ( 48 <= (*p) && (*p) <= 57 )
		goto st4;
	goto tr144;
tr141:
#line 1 "NONE"
	{te = p+1;}
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st88;
st88:
	if ( ++p == pe )
		goto _test_eof88;
case 88:
#line 1915 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr28;
		case 32: goto tr28;
		case 46: goto st16;
		case 58: goto tr30;
		case 95: goto st16;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr28;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st16;
		} else if ( (*p) >= 65 )
			goto st16;
	} else
		goto st16;
	goto tr144;
tr142:
#line 1 "NONE"
	{te = p+1;}
#line 33 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st89;
st89:
	if ( ++p == pe )
		goto _test_eof89;
case 89:
#line 1943 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr28;
		case 32: goto tr28;
		case 46: goto st16;
		case 58: goto tr30;
		case 95: goto st16;
		case 116: goto st35;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr28;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 97 <= (*p) && (*p) <= 122 )
				goto st16;
		} else if ( (*p) >= 65 )
			goto st16;
	} else
		goto st16;
	goto tr144;
tr143:
#line 1 "NONE"
	{te = p+1;}
#line 32 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
#line 37 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START;}
	goto st90;
st90:
	if ( ++p == pe )
		goto _test_eof90;
case 90:
#line 1972 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 9: goto tr28;
		case 32: goto tr28;
		case 46: goto st16;
		case 58: goto tr30;
		case 95: goto st16;
		case 97: goto st53;
	}
	if ( (*p) < 48 ) {
		if ( 11 <= (*p) && (*p) <= 12 )
			goto tr28;
	} else if ( (*p) > 57 ) {
		if ( (*p) > 90 ) {
			if ( 98 <= (*p) && (*p) <= 122 )
				goto st16;
		} else if ( (*p) >= 65 )
			goto st16;
	} else
		goto st16;
	goto tr144;
tr151:
#line 58 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{te = p+1;}
	goto st91;
tr154:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{LINE_START;}
#line 59 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{te = p;p--;}
	goto st91;
tr155:
#line 58 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{te = p;p--;}
	goto st91;
st91:
#line 1 "NONE"
	{ts = 0;}
	if ( ++p == pe )
		goto _test_eof91;
case 91:
#line 1 "NONE"
	{ts = p;}
#line 2008 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	switch( (*p) ) {
		case 10: goto tr152;
		case 13: goto tr153;
	}
	goto tr151;
tr152:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
#line 59 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{{goto st77;}}
	goto st92;
tr156:
#line 59 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{{goto st77;}}
	goto st92;
st92:
	if ( ++p == pe )
		goto _test_eof92;
case 92:
#line 2024 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	goto tr154;
tr153:
#line 31 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"
	{MATCH_START + 1; TOKEN_WO_LEXEME(TOKEN_NEWLINE); ++current_line;}
	goto st93;
st93:
	if ( ++p == pe )
		goto _test_eof93;
case 93:
#line 2032 "/home/pmt/repos/pmt-logera-c/lib/lexer.c"
	if ( (*p) == 10 )
		goto tr156;
	goto tr155;
	}
	_test_eof77: cs = 77; goto _test_eof; 
	_test_eof78: cs = 78; goto _test_eof; 
	_test_eof0: cs = 0; goto _test_eof; 
	_test_eof79: cs = 79; goto _test_eof; 
	_test_eof1: cs = 1; goto _test_eof; 
	_test_eof2: cs = 2; goto _test_eof; 
	_test_eof3: cs = 3; goto _test_eof; 
	_test_eof4: cs = 4; goto _test_eof; 
	_test_eof5: cs = 5; goto _test_eof; 
	_test_eof6: cs = 6; goto _test_eof; 
	_test_eof7: cs = 7; goto _test_eof; 
	_test_eof8: cs = 8; goto _test_eof; 
	_test_eof9: cs = 9; goto _test_eof; 
	_test_eof10: cs = 10; goto _test_eof; 
	_test_eof11: cs = 11; goto _test_eof; 
	_test_eof12: cs = 12; goto _test_eof; 
	_test_eof13: cs = 13; goto _test_eof; 
	_test_eof80: cs = 80; goto _test_eof; 
	_test_eof14: cs = 14; goto _test_eof; 
	_test_eof15: cs = 15; goto _test_eof; 
	_test_eof16: cs = 16; goto _test_eof; 
	_test_eof17: cs = 17; goto _test_eof; 
	_test_eof18: cs = 18; goto _test_eof; 
	_test_eof19: cs = 19; goto _test_eof; 
	_test_eof20: cs = 20; goto _test_eof; 
	_test_eof21: cs = 21; goto _test_eof; 
	_test_eof81: cs = 81; goto _test_eof; 
	_test_eof22: cs = 22; goto _test_eof; 
	_test_eof23: cs = 23; goto _test_eof; 
	_test_eof24: cs = 24; goto _test_eof; 
	_test_eof25: cs = 25; goto _test_eof; 
	_test_eof26: cs = 26; goto _test_eof; 
	_test_eof27: cs = 27; goto _test_eof; 
	_test_eof28: cs = 28; goto _test_eof; 
	_test_eof29: cs = 29; goto _test_eof; 
	_test_eof30: cs = 30; goto _test_eof; 
	_test_eof31: cs = 31; goto _test_eof; 
	_test_eof82: cs = 82; goto _test_eof; 
	_test_eof32: cs = 32; goto _test_eof; 
	_test_eof33: cs = 33; goto _test_eof; 
	_test_eof34: cs = 34; goto _test_eof; 
	_test_eof35: cs = 35; goto _test_eof; 
	_test_eof36: cs = 36; goto _test_eof; 
	_test_eof37: cs = 37; goto _test_eof; 
	_test_eof38: cs = 38; goto _test_eof; 
	_test_eof39: cs = 39; goto _test_eof; 
	_test_eof40: cs = 40; goto _test_eof; 
	_test_eof41: cs = 41; goto _test_eof; 
	_test_eof42: cs = 42; goto _test_eof; 
	_test_eof43: cs = 43; goto _test_eof; 
	_test_eof83: cs = 83; goto _test_eof; 
	_test_eof44: cs = 44; goto _test_eof; 
	_test_eof45: cs = 45; goto _test_eof; 
	_test_eof46: cs = 46; goto _test_eof; 
	_test_eof47: cs = 47; goto _test_eof; 
	_test_eof48: cs = 48; goto _test_eof; 
	_test_eof49: cs = 49; goto _test_eof; 
	_test_eof50: cs = 50; goto _test_eof; 
	_test_eof51: cs = 51; goto _test_eof; 
	_test_eof52: cs = 52; goto _test_eof; 
	_test_eof53: cs = 53; goto _test_eof; 
	_test_eof54: cs = 54; goto _test_eof; 
	_test_eof55: cs = 55; goto _test_eof; 
	_test_eof56: cs = 56; goto _test_eof; 
	_test_eof57: cs = 57; goto _test_eof; 
	_test_eof58: cs = 58; goto _test_eof; 
	_test_eof59: cs = 59; goto _test_eof; 
	_test_eof60: cs = 60; goto _test_eof; 
	_test_eof61: cs = 61; goto _test_eof; 
	_test_eof62: cs = 62; goto _test_eof; 
	_test_eof63: cs = 63; goto _test_eof; 
	_test_eof64: cs = 64; goto _test_eof; 
	_test_eof84: cs = 84; goto _test_eof; 
	_test_eof65: cs = 65; goto _test_eof; 
	_test_eof66: cs = 66; goto _test_eof; 
	_test_eof67: cs = 67; goto _test_eof; 
	_test_eof68: cs = 68; goto _test_eof; 
	_test_eof69: cs = 69; goto _test_eof; 
	_test_eof70: cs = 70; goto _test_eof; 
	_test_eof71: cs = 71; goto _test_eof; 
	_test_eof72: cs = 72; goto _test_eof; 
	_test_eof73: cs = 73; goto _test_eof; 
	_test_eof74: cs = 74; goto _test_eof; 
	_test_eof75: cs = 75; goto _test_eof; 
	_test_eof76: cs = 76; goto _test_eof; 
	_test_eof85: cs = 85; goto _test_eof; 
	_test_eof86: cs = 86; goto _test_eof; 
	_test_eof87: cs = 87; goto _test_eof; 
	_test_eof88: cs = 88; goto _test_eof; 
	_test_eof89: cs = 89; goto _test_eof; 
	_test_eof90: cs = 90; goto _test_eof; 
	_test_eof91: cs = 91; goto _test_eof; 
	_test_eof92: cs = 92; goto _test_eof; 
	_test_eof93: cs = 93; goto _test_eof; 

	_test_eof: {}
	if ( p == eof )
	{
	switch ( cs ) {
	case 78: goto tr144;
	case 0: goto tr0;
	case 79: goto tr145;
	case 1: goto tr0;
	case 2: goto tr0;
	case 3: goto tr0;
	case 4: goto tr0;
	case 5: goto tr0;
	case 6: goto tr0;
	case 7: goto tr0;
	case 8: goto tr0;
	case 9: goto tr0;
	case 10: goto tr0;
	case 11: goto tr0;
	case 12: goto tr0;
	case 13: goto tr0;
	case 80: goto tr146;
	case 14: goto tr0;
	case 15: goto tr0;
	case 16: goto tr0;
	case 17: goto tr0;
	case 18: goto tr0;
	case 19: goto tr0;
	case 20: goto tr0;
	case 21: goto tr0;
	case 81: goto tr147;
	case 22: goto tr0;
	case 23: goto tr0;
	case 24: goto tr0;
	case 25: goto tr0;
	case 26: goto tr0;
	case 27: goto tr0;
	case 28: goto tr0;
	case 29: goto tr0;
	case 30: goto tr0;
	case 31: goto tr0;
	case 82: goto tr148;
	case 32: goto tr0;
	case 33: goto tr0;
	case 34: goto tr0;
	case 35: goto tr0;
	case 36: goto tr0;
	case 37: goto tr0;
	case 38: goto tr0;
	case 39: goto tr0;
	case 40: goto tr0;
	case 41: goto tr0;
	case 42: goto tr0;
	case 43: goto tr0;
	case 83: goto tr149;
	case 44: goto tr0;
	case 45: goto tr0;
	case 46: goto tr0;
	case 47: goto tr0;
	case 48: goto tr0;
	case 49: goto tr0;
	case 50: goto tr0;
	case 51: goto tr0;
	case 52: goto tr0;
	case 53: goto tr0;
	case 54: goto tr0;
	case 55: goto tr0;
	case 56: goto tr0;
	case 57: goto tr0;
	case 58: goto tr0;
	case 59: goto tr0;
	case 60: goto tr0;
	case 61: goto tr0;
	case 62: goto tr0;
	case 63: goto tr0;
	case 64: goto tr0;
	case 84: goto tr150;
	case 65: goto tr0;
	case 66: goto tr0;
	case 67: goto tr0;
	case 68: goto tr0;
	case 69: goto tr0;
	case 70: goto tr0;
	case 71: goto tr0;
	case 72: goto tr0;
	case 73: goto tr0;
	case 74: goto tr0;
	case 75: goto tr0;
	case 76: goto tr0;
	case 85: goto tr144;
	case 86: goto tr144;
	case 87: goto tr144;
	case 88: goto tr144;
	case 89: goto tr144;
	case 90: goto tr144;
	case 92: goto tr154;
	case 93: goto tr155;
	}
	}

	}

#line 219 "/home/pmt/repos/pmt-logera-c/lib/lexer.rl"

            // How much is still at the end of the buffer?
        leftover = data + len - pe;

        // Move the leftovers to the beginning of the buffer.
        memmove(buffer, pe, leftover);
    }
    while(!terminated_reader_done(reader));

ret_stmt:
    terminated_reader_destroy(reader);
    return records;
}
