// Generated by Flexc++ V2.11.01 on Sat, 24 Sep 2022 22:46:28 +0200

#ifndef HeaderScanner_H_INCLUDED_
#define HeaderScanner_H_INCLUDED_

// $insert baseclass_h
#include "header_scannerbase.h"


// $insert classHead
class HeaderScanner: public HeaderScannerBase
{
    public:
        #include "header_tokens.hi"

        explicit HeaderScanner(std::istream &in = std::cin, std::ostream &out = std::cout, bool keepCwd = true);

        HeaderScanner(std::string const &infile, std::string const &outfile, bool keepCwd = true);
        
        // $insert lexFunctionDecl
        int lex();

    private:
        int lex_();
        int executeAction_(size_t ruleNr);

        void print();
        void preCode();     // re-implement this function for code that must 
                            // be exec'ed before the patternmatching starts

        void postCode(PostEnum_ type);    
                            // re-implement this function for code that must 
                            // be exec'ed after the rules's actions.
};

// $insert scannerConstructors
inline HeaderScanner::HeaderScanner(std::istream &in, std::ostream &out, bool keepCwd)
:
    HeaderScannerBase(in, out, keepCwd)
{}

inline HeaderScanner::HeaderScanner(std::string const &infile, std::string const &outfile, bool keepCwd)
:
    HeaderScannerBase(infile, outfile, keepCwd)
{}

// $insert inlineLexFunction
inline int HeaderScanner::lex()
{
    return lex_();
}

inline void HeaderScanner::preCode() 
{
    // optionally replace by your own code
}

inline void HeaderScanner::postCode([[maybe_unused]] PostEnum_ type) 
{
    // optionally replace by your own code
}

inline void HeaderScanner::print() 
{
    print_();
}


#endif // HeaderScanner_H_INCLUDED_

