// Generated by Flexc++ V2.14.00 on Tue, 07 Nov 2023 22:45:52 +0100

#ifndef log_scanner_H_INCLUDED_
#define log_scanner_H_INCLUDED_

// $insert baseclass_h
#include "log_scanner_base.h"


// $insert classHead
class log_scanner: public log_scannerBase
{
    public:
        explicit log_scanner(std::string const& infile);
        
        // $insert lexFunctionDecl
        int lex();

    private:
        int lex_();
        int executeAction_(size_t ruleNr);

        void print();
        void preCode();     // re-implement this function for code that must 
                            // be exec'ed before the patternmatching starts

        void postCode(PostEnum_ type);    
                            // re-implement this function for code that must 
                            // be exec'ed after the rules's actions.
};

inline log_scanner::log_scanner(std::string const &infile)
:
    log_scannerBase(infile, "-")
{}

// $insert inlineLexFunction
inline int log_scanner::lex()
{
    return lex_();
}

inline void log_scanner::preCode() 
{
    // optionally replace by your own code
}

inline void log_scanner::postCode([[maybe_unused]] PostEnum_ type) 
{
    // optionally replace by your own code
}

inline void log_scanner::print() 
{
    print_();
}


#endif // log_scanner_H_INCLUDED_

