// Generated by Bisonc++ V6.04.04 on Fri, 07 Oct 2022 23:03:09 +0200

#ifndef LogParser_h_included
#define LogParser_h_included

// $insert baseclass
#include "log_parserbase.h"
// $insert scanner.h
#include "log_scanner.h"

#include "log_scanner.h"
#include "parse_error.h"

#include <fstream>
#include <filesystem>
#include <optional>

struct log_data;
class log_parser_context;

class log_parser : public log_parserBase {

    // $insert scannerobject
    log_scanner d_scanner;
    std::string const& d_matched;
    
    log_parser_context& m_ctx;
    std::optional<parse_error> m_error_info;

public:
    log_parser(std::filesystem::path const& path, log_parser_context& ctx);
    int parse();
    std::unique_ptr<log_data> gen();
    parse_error const& get_error_info() const;

private:
    void error(); // called on (syntax) errors
    int  lex(); // returns the next token from the
        // lexical scanner.
    void print(); // use, e.g., d_token, d_loc
    void exceptionHandler(std::exception const& exc);

    // support functions for parse():
    void executeAction_(int ruleNr);
    void errorRecovery_();
    void nextCycle_();
    void nextToken_();
    void print_();
};

#endif
